[project]
name = "clear-my-fridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "rapidfuzz>=3.13.0",
    "requests>=2.32.5",
    "streamlit>=1.49.0",
]
